### ISSUE TITLE
Invalid XML and missing data sent to the client when *not* omitting XML

### ISSUE THREAD

**Issue by nstockton** [MUME/MMapper#101]
Hello,
I was recently experimenting with running my own mapper on top of the MMapper raw XML mode, in order to benefit from the group manager among other things. I have found a few issues with MMapper's raw mode, mainly because it doesn't appear to be a true XML pass-through of the game's XML.

1.  MMapper's raw output does not include the contents of gratuitous elements. the gratuitous and description tags are there, but the actual room description is missing. The exits element is similarly affected. While the exits line is sent to the client, it is outside of the <exits></exits> tags. I suspect it's omitting the exits line sent by mume, and substituting it outside of the tags, even though I have the show emulated exits check box unchecked.
2.  <, >, &, ', and ", should be replaced with the entity references `&lt;, &gt;, &amp;, &apos;, and &quot;` in all strings, except obviously the beginning and end of tags themselves. Mume's XML output does this, MMapper's raw output does not. This understandably leads to any XML parser that sits on top of the MMapper raw XML connection becoming unstable and data being lost.
3.  When in raw mode, MMapper fails to enclose emulated prompts in <prompt></prompt> tags. This happens for example when the player receives a group tell from the group manager. This coupled with the '>' sign in the prompt not being replaced with `'&gt;'` meant my XML parser was breaking quite frequently.

Thanks very much.

**Comment by nschimme** [comment]
The simplest solution would be to just pass through the input directly to the mud client without any tampering.

**Comment by nstockton** [comment]
I agree. I thought about trying to run MMapper on top of my mapper instead of the other way round, but that still will sadly not fix it breaking the Mume XML plugin for MushClient that I wrote.

Basically, my current setup is to use my mapper in raw output mode. In this mode, all XML data is passed to MushClient unmodified. MushClient then uses the Mume XML plugin to parse the XML, and broadcast events for different tags for the plugins that subscribe to those events. For example, the communication plugin subscribes to tell, narrate, say, emote, and pray events, and handles the logging when they're received. the secret exits database subscribes to the room name event and uses it when it is received, and another plugin subscribes to the prompt event when it's received, and stores the different information contained in the prompt in separate variables so they can be spoken with keyboard macros. I'd like to be able to add MMapper to the mix so that I can use group manager, but have a feeling I'll need to sit down and figure out the details of the group manager protocol so I can add it to my mapper directly.

**Comment by nschimme** [comment]
@nstockton try the latest build on master. I added support for you
