### ISSUE TITLE
JSON error creating dir v1

### ISSUE THREAD

**Issue by fille** [MUME/MMapper#108]
trying to export a map to json 

getting the following error  "error creating dir v1"

**Comment by nschimme** [comment]
This might not be a valid bug. I was able to save json directories myself on Linux.

@fille, where were you trying to save the map? What OS were you using?

**Comment by fille** [comment]
i compiled the src on OS X and also downloaded the binaries  on Windows 10. tried to run it with sudo and as administrator in windows. i will look into it again and try to repoduce it
