### ISSUE TITLE
Graphics glitch regression in MMapper 2.3.3 

### ISSUE THREAD

**Issue by johannesclaesson** [MUME/MMapper#12]
Using the "move map" option, the map moves very slowly and locks up responsiveness of application. It seems that it re-draws the entire map for each pixel moved in any direction. This behaviour is not seen with version 2.2.1.

Attachment: Movie uploaded for reference. Note that it is an mkv movie uploaded as gif to trick github file upload permissions.
![mmapper233bug](https://cloud.githubusercontent.com/assets/10914172/6099194/940eb2ae-aff2-11e4-99a3-1797241206a4.gif)

**Comment by nschimme** [comment]
I'm assuming you're using a Mac? Can you share your hardware specs? My Macbook Pro (Retina, Mid 2012) doesn't exhibit the slowness problem.

The font error is a real issue though. That is related to this issue: https://github.com/MUME/MMapper/issues/2

**Comment by johannesclaesson** [comment]
Linux. Nvidia 660gtx, proprietary binary blob driver 340. Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz. Linux 3.18.0-8-generic #9-Ubuntu SMP Mon Jan 5 22:51:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux.

Don't have the issues on my Linux laptop with si

**Comment by nschimme** [comment]
Is this problem fixed now? Please re-open if not.
