### ISSUE TITLE
Modernize Codebase to C++11

### ISSUE THREAD

**Issue by nschimme** [MUME/MMapper#124]
We need to modernize the codebase to identify bugs.

**Comment by JustinKey187** [comment]
Hello! i don't have much time atm to look over all the code but i did notice few manual destructors. C++11 allows destructors to be automatically called when going out of scope. imo doing something manually when i will occur naturally may lead to future bugs. I just started github and have been practicing code for the past few years, i would like to help update this project.

**Comment by nschimme** [comment]
Hey Justin,

I'm already working on this particular ticket. If you want to help I would
suggest you wait another few weeks.

Best,
Nils

**Comment by nschimme** [comment]
We should take a look at utilizing clazy (https://github.com/KDE/clazy) to do static analysis on the code and modernize the signals/slots logic.

**Comment by JustinKey187** [comment]
That’s fine. Thanks for the heads up!

Sent from my iPhone

On Jul 27, 2018, at 12:33 PM, Nils Schimmelmann <notifications@github.com<mailto:notifications@github.com>> wrote:


We should take a look at utilizing clazy (https://github.com/KDE/clazy) to do static analysis on the code and modernize the signals/slots logic.
