### ISSUE TITLE
Map is altered in play mode

### ISSUE THREAD

**Issue by nschimme** [MUME/MMapper#138]
Fog, trails, and other non-trivial details auto-update the map in play mode even though the map should be completely static.

**Comment by Atastor** [comment]
Care to elaborate? Never noticed this

**Comment by nschimme** [comment]
`RoomFactory.compareWeakProps()` has a state where if it is `TOLERANT` it will update the map irrespective of the map mode.

**Comment by nschimme** [comment]
Code that is most likely updating the rooms:
https://github.com/MUME/MMapper/blob/master/src/pathmachine/approved.cpp#L42-L44

**Comment by nschimme** [comment]
https://github.com/MUME/MMapper/commit/36059bec9279178710afd32c533205838945f862
