### ISSUE TITLE
Missing MSVCR120.dll

### ISSUE THREAD

**Issue by graphiclife** [MUME/MMapper#143]
Downloaded the MMapper 2.7.4 for Windows and upon starting I'm greeted with a System Error alert stating "The code execution cannot proceed because MSVCR120.dll was not found. Reinstalling the program may fix this problem."

**Comment by graphiclife** [comment]
Running Windows 10. Latest updates.

**Comment by tomaswindsor** [comment]
You need to install "Visual C++ Redistributable Packages for Visual Studio 2013". It can be downloaded at microsoft site here: https://www.microsoft.com/en-us/download/details.aspx?id=40784
I think current windows build of mmapper is 32bit so you will need the 32bit version of the packages installed (can install both 32bit and 64bit tho).

**Comment by nschimme** [comment]
This will be fixed in the next MMapper release. You can use the link mentioned in an earlier comment to install the VS2013 runtime.

https://github.com/MUME/MMapper/commit/68f640488246bb025a020d90aa3a13de046c967c
https://github.com/MUME/MMapper/commit/d72519876f58c540e9fbdf0f49d8453d354d05e1

**Comment by graphiclife** [comment]
@nschimme @tomaswindsor Works!, Thanks alot for quick response! <3
