### ISSUE TITLE
Map display not reacting to client connection in Win 7

### ISSUE THREAD

**Issue by emptyerik** [MUME/MMapper#144]
When running in Win7, the map doesn't react to a client connection.  The client can connect and login to MUME, but the launch panel doesn't disappear and the map area on the left is either black or doesn't go to the current room.  This behavior is on v19.04 using either mudlet or the Integrated mud client.  It works in Linux environment.  I tried changing modes, reloading map, reinstalling software... can't figure it out.

**Comment by nschimme** [comment]
What happens if you disable Software rendering under Preferences > Graphics?

**Comment by emptyerik** [comment]
That worked after the restart - thanks!
