### ISSUE TITLE
Automatically generate checksum files for future releases

### ISSUE THREAD

**Issue by nstockton** [MUME/MMapper#148]
I have recently been working on a script to auto-update MMapper on Windows for a friend, based on the code I use to update my own mapper. While I can verify that the downloaded file size is the same as the size reported by the GitHub API, I would like to use a checksum to properly verify that the file is complete and genuine, like I do in my own project. If it's not too much trouble, would you be willing to generate checksums for assets as part of the build process for MMapper?
Looking at the .appveyor.yml file, if you add the following line to the end of the build_script section, SHA256 checksums for the generated .zip and .exe files should be generated. (tested on my computer using Power Shell Core 6 in the path)

```
pwsh.exe -Command "foreach ($file in Get-ChildItem -Path c:\Build\MMapper\winbuild\* -Include *.zip,*.exe -File) { (Get-FileHash $file -Algorithm SHA256).Hash.ToString().ToLower() + \" *$($file.Name)`n\" | Set-Content -Encoding UTF8NoBOM -Path \"$file.sha256\" -NoNewLine }"
```

If you wanted to call it from within a Power Shell Core script directly, you would need to unescape the double quotes like this.

```
foreach ($file in Get-ChildItem -Path c:\Build\MMapper\winbuild\* -Include *.zip,*.exe -File) { (Get-FileHash $file -Algorithm SHA256).Hash.ToString().ToLower() + " *$($file.Name)`n" | Set-Content -Encoding UTF8NoBOM -Path "$file.sha256" -NoNewLine }
```

Note that use of the UTF8NoBOM encoding requires Power Shell Core as it does not exist in the normal Power Shell. If using normal Power Shell (A.K.A V5 and lower), ASCII needs to be used instead. Normal Power Shell does have a UTF8 encoding, but using it causes a BOM to be prepended to the beginning of the file, which causes the Unix versions of sha256sum to choke.
The format recognized by 'sha256sum -c file' is:

```
HexValueOfHash *path\n
```

**Comment by nschimme** [comment]
Let see if I can do this in an more generic manner using CPack:

https://cmake.org/cmake/help/v3.7/module/CPack.html
CPACK_PACKAGE_CHECKSUM

**Comment by nstockton** [comment]
CPack definitely looks to be the better way of doing this.

**Comment by nschimme** [comment]
Packaging them now on AppVeyor. I'll include them going forward as part of Github releases.

https://github.com/MUME/MMapper/commit/657f952cf7c5af4e2abc2e597f4fc55dce87a30a

**Comment by nstockton** [comment]
Thank you very much. This will be a big help.
