### ISSUE TITLE
Hinting the location of distant players

### ISSUE THREAD

**Issue by tomaswindsor** [MUME/MMapper#17]
It would be nice if MMapper hinted the direction of other connected players via group-manager in case their location is not rendered in currently visible part of the map.
Something like a small line or dot of player's colour would be rendered at border of the rendered map at appropriate position.

**Comment by nschimme** [comment]
I've taken a stab at it and managed to learn some basic OpenGL in the process. Should be able to get in as part of 2.4.0 :-)

**Comment by tomaswindsor** [comment]
Take a look at [game-play of old Atari 8-bit game Getaway](https://www.youtube.com/watch?v=GI7XGChVjd0) which implements that feature for distant sprites for inspiration.

**Comment by nschimme** [comment]
Heh, much simpler than my solution of using an ellipse. Give the current solution a try and see if you hate it. I can change it easily to match the Atari game.

**Comment by tomaswindsor** [comment]
It would be nice to be able to exclude some of the connected players from this feature. Ideally even from ever appearing in the group manager listing. (sometimes ppl use "virtual" player as a server and it's annoying to see arrow to this player all the time)
Also the arrows could be somewhat smaller (or have their size configurable).
