### ISSUE TITLE
canvas devicePixelRatio not updated when moving between monitors

### ISSUE THREAD

**Issue by ethorondil** [MUME/MMapper#183]
I have two monitors, one of which has HiDPI and the other of which does not; that is, `QPaintDevice::devicePixelRatioF()` is 1 on one monitor and 2 on the other.

When mmapper is run on my primary display (pixel ratio 1), everything works as normal.  When I drag it to the high-resolution display, the menu text and icons grow in size (as expected), but the map is only displayed on the bottom left quarter of the available area -- the other 3/4 of the map area is a blank gray. (The _interface_ for the map does not realize this, however: if I click to select a room, it will actually select the one half-way to the bottom left corner from there.)

If I artificially change the line

`gl.initializeRenderer(static_cast<float>(QPaintDevice::devicePixelRatioF()))
`
in `src/display/mapcanvas_gl.cpp` to multiply the input by 2, then MMapper works perfectly on my high-resolution display but not my low-resolution one.  Presumably the parameter this affects (`Legacy::Functions.m_devicePixelRatio`) needs to be updated (perhaps on QWindow::screenChanged() ?).

**Comment by nschimme** [comment]
Thanks for the investigation! I just bought a 4K monitor and will be doing some testing myself later. Let's continue investigating in ticket https://github.com/MUME/MMapper/issues/180
