### ISSUE TITLE
Strange font issues on osx

### ISSUE THREAD

**Issue by git-celerus** [MUME/MMapper#2]
Running the mac release i'm running into garbled font issues and am unable to edit existing info marks.  
![screen shot 2015-02-02 at 6 53 02 pm](https://cloud.githubusercontent.com/assets/10822622/6013736/992b2e3c-ab0d-11e4-86cb-0a153e9b1b38.png)

This happens on both the latest release and when I built from source.

**Comment by nschimme** [comment]
Interesting, is this with a retina display?

**Comment by git-celerus** [comment]
Yes, it's on a retina macbook pro.  Strangely enough, on starting the app the rendering looks fine, but when the map is moved a few spaces, either dragged manually or as it follows, it garbles the text as in the picture.

**Comment by nschimme** [comment]
Seems related to this bug in Qt: https://bugreports.qt.io/browse/QTBUG-41105

2015-02-02 21:56 GMT-08:00 git-celerus <notifications@github.com>:

**Comment by nschimme** [comment]
We should at some point code in proper DPI scaling support into MMapper. If you want to give this a try feel free to take it on. There are several examples in the bug above.

**Comment by nschimme** [comment]
I've tried building the latest version of MMapper with Qt 5.4.1 and the issue is still here. We're probably going to switch to a different way of rendering text for this to be fixed correctly. The DPI comment I mentioned above might do the trick.

**Comment by nschimme** [comment]
After a lot of investigations I've noticed that QGLWidget has essentially been deprecated in Qt5. The proper solution is to completely step away from this widget and render everything with native OpenGL.

A smart solution might be to get away from OpenGL entirely and just use the QtGui packages. Most computers are fast enough these days and OpenGL's longterm lifespan is questionable given that a lot  of work is now being put into OpenGL's Vulkan.
