### ISSUE TITLE
Does not run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [MUME/MMapper#203]
Does not run on Ubuntu xenial. Please build on xenial or older, thank you.

Reference:
https://github.com/AppImage/appimage.github.io/pull/2132

**Comment by nschimme** [comment]
@probonopd MMapper uses OpenSSL for network connectivity and I didn't want to package an older OpenSSL 1.0.x library within the AppImage. Until we have a good solution for this problem, I am opting to only support OpenSSL 1.1.x and higher which meant supporting Bionic as the lowest supported distro. Any thoughts on this?

**Comment by probonopd** [comment]
Thanks @nschimme. That dreaded OpenSSL issue again. Someone recently suggested to make 2 AppImages, one for OpenSSL 1.0.x systems and one for OpenSSL 1.1.x+ systems. Not elegant but pragmatic ;-/

**Comment by nschimme** [comment]
@probonopd is there a reason why we haven't moved on to bionic yet? Looking at  xenial under https://wiki.ubuntu.com/Releases it is now at "End of Standard Support". Technically even trusty has "End of Life" until 2024. What are the rules that we are following? "End of Life" or "End of Standard Support"?

I'm of the opinion that we should move on to bionic for security reasons (i.e. OpenSSL 1.1.x and TLS 1.3).

**Comment by probonopd** [comment]
Indeed, bionic is the new target now. We are now running the tests on bionic.

**Comment by nschimme** [comment]
Does that mean this issue is now or soon invalid? :-)

**Comment by probonopd** [comment]
Indeed. Hence, closing. Thanks for checking back.
