### ISSUE TITLE
removing light status from the prompt causes update failure

### ISSUE THREAD

**Issue by nate2s** [MUME/MMapper#221]
Removing the light status from the prompt via `cha prompt light` causes the mapper to fail to update when moving. The mapper will periodically update but very sporadically.

While walking from Rivendell to Bree, the mapper would never update on Old East Road. But it would update on any other room. Rebooting the mapper didn't help.

Once I added the light status back to the prompt, the issue went away.

**Comment by nschimme** [comment]
Fixed in https://github.com/MUME/MMapper/commit/dfd99d11f987ddd25a8713371949d078a32c7c2d
