### ISSUE TITLE
add an image marker for milkable animals to the map

### ISSUE THREAD

**Issue by cuantar** [MUME/MMapper#224]
It can be implemented similarly to other room flags, such as `aggmob`, `water`, `dark`, ...  There should be a command interface like

`_room flags +moo`

and an icon in a corner of the room's map tile with a picture of a cow or a similar.

**Comment by cuantar** [comment]
![image](https://user-images.githubusercontent.com/76072786/121770863-ea55d480-cb39-11eb-80b7-c2a984b11923.png)

**Comment by cuantar** [comment]
https://www.pngwing.com/en/free-png-swwlm

**Comment by cuantar** [comment]
implemented in #227

**Comment by nschimme** [comment]
https://github.com/MUME/MMapper/commit/21c665836f47550d78847cba0a05fae409c42011
