### ISSUE TITLE
Cannot mod room textures if using AppImage

### ISSUE THREAD

**Issue by fletchersam** [MUME/MMapper#234]
When using MMapper AppImage, the resource directory is not created, so there is no way to use custom room textures.

**Comment by nschimme** [comment]
Alternatively you can also configure MMapper to use a different directory for Resources under the Graphics preferences

**Comment by fletchersam** [comment]
Maybe I am missing something (entirely possible). It is not just the directory itself, but the contents as well. I can't find anywhere where MMapper is storing and looking for the .png files.

My understanding (assumption) was that in, say, a Windows installation, MMapper would have a directory (like the resources directory) in which all of the texture .png files were, and to mod them one would go in and change out the .png files. Perhaps I am not even looking for the right thing?

**Comment by fletchersam** [comment]
Oh my. Now I see what I missed. I skipped the step to create the pixmaps directory under Resources. I was putting .png files right under Resources. Doing exactly what the instructions said works like a charm.

So, I guess the request here is to, um, teach me to read instructions better? ;-)

**Comment by nschimme** [comment]
Glad you figured it out :-)
