### ISSUE TITLE
Very slight corruption damage found in official map

### ISSUE THREAD

**Issue by cosmos72** [MUME/MMapper#247]
As told in-game to Jahara, testing the new feature "Export to MMapper2 XML Map As...",
I found a small damage in the official map https://github.com/MUME/MMapper/releases/download/v21.12.1/arda.mm2

The damage is: room 131998 (a deathtrap at coordinates x=215, y=-124, z=0) has
- RoomAlignEnum=190
- RoomLightEnum=190
- RoomPortableEnum=190
- RoomRidableEnum=190
- RoomSundeathEnum=190

which are clearly invalid.

How to locate it: it's the DT one east of northernmost "On a Very Narrow Ledge" in Big John area

While it does not directly affect gameplay (since it's a deathtrap), it's dangerous because it loads
unexpected and out-of-range enum values inside the C++ in-memory map representation,
which may cause undefined behaviour (BAD! means anything could happen, including a MMapper2 crash or more corruption)
depending on the compiler's interpretation of the C++ standard - see
http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#1766

[UPDATE] since all enums in MMapper2 source code are defined as `enum class NODISCARD ...`
it seems that the conversion of an out-of-range enum value merely produces an unspecified value,
not an undefined behaviour.
For details, see (hoping that's it correct and updated, and that compilers actually comply with it)
https://wiki.sei.cmu.edu/confluence/display/cplusplus/INT50-CPP.+Do+not+cast+to+an+out-of-range+enumeration+value

**Comment by nschimme** [comment]
I believe I resolved this
