### ISSUE TITLE
Option to hide bottom status bar (and possibly scrollbars)

### ISSUE THREAD

**Issue by mdrcode** [MUME/MMapper#251]
Thank you for the amazing work on this project!

When we record videos for Youtube, we try to compose the map on top of the MUD client. It would be super helpful if we could hide the bottom status bar (the UI element with the season / time of day) and possibly even the scrollbars. They take up a big chunk of real estate when we are trying to compose a screen for Youtube Shorts, etc.

An option under the View... menu for Scrollbars and possibly Toolbars > Bottom Status Bar would be amazing!

**Comment by mdrcode** [comment]
It looks sexy!

<img width="835" alt="Screen Shot 2022-12-28 at 8 40 19 PM" src="https://user-images.githubusercontent.com/56870/209904259-30daf942-5551-49b3-b956-1f1541a337c0.png">

**Comment by nschimme** [comment]
I merged this @mdrcode , Congratulations on your first contribution! 🥳
