### ISSUE TITLE
Escape sequence seen in mmapper terminal

### ISSUE THREAD

**Issue by Sebster7** [MUME/MMapper#260]
Escape sequence seen in mmapper terminal:
`![ iM 2[0:2]>
You have been idle, and are pulled into a void.

!f iM 0[0:0]>
Marilyn prays '<3'

!f iM 0[0:0]>
[K
Legault prays 'Kit please.'

of iM 0[0:0]>
[K
l
[KGarden of the Ainur`

**Comment by nschimme** [comment]
This is using the built-in client?

**Comment by Sebster7** [comment]
> This is using the built-in client?

Yes, it was.
