### ISSUE TITLE
Non-black exit colors (for GL_STIPPLE lines) are displayed grey.

### ISSUE THREAD

**Issue by teoli2003** [MUME/MMapper#28]
This got broken at some point between 2.2.1 and 2.3.6.

Depending of the exit flag, the stipple line should have different colors. In 2.3.6, all are grey.
Strangely, when the room is selected, the right color appear.

Example of an area where the stipple lines are grey instead of a color:
<img width="354" alt="screen shot 2016-12-17 at 18 17 05" src="https://cloud.githubusercontent.com/assets/1466293/21288831/17bd6c32-c485-11e6-9357-e352e81ccfc2.png">

If we "select" one of the room, the expected color does appear:
<img width="291" alt="screen shot 2016-12-17 at 18 17 22" src="https://cloud.githubusercontent.com/assets/1466293/21288833/305fe440-c485-11e6-86b1-bb988147e1fe.png">

Likely something easy, but I wasn't able to find it.

**Comment by nschimme** [comment]
Most likely broke when I migrated to Qt5 and add retina support. I also noticed that there is a regression in rooms in negative z layers.

**Comment by nschimme** [comment]
I think the only real solution is a rewrite of the OpenGL canvass. The code is a big mess and we really ought to migrate to Vulkan instead.

**Comment by nschimme** [comment]
@teoli2003 please let me know if the latest PR fixes the issue

**Comment by nschimme** [comment]
I realized that @teoli2003 fixed this in https://github.com/MUME/MMapper/pull/23
