### ISSUE TITLE
Can't move east just before Bree

### ISSUE THREAD

**Issue by lofijeff** [MUME/MMapper#292]
Well I mean the game moves me on, but the mmapper stops right there. I'm on linux, using the 22.05.0-1.

**Comment by nschimme** [comment]
You should try upgrading MMapper as nobody else has this issue. Also, the map you're on is ancient and you'll probably need a newer one.

**Comment by mvancleave99** [comment]
This is 100% an issue with an old map that doesn't include the Breelands updates. This is exactly what happens to me if I have an older map loaded.

**Comment by nschimme** [comment]
Map issues aren't specific to the code base. Closing as a user needs to fix their map.
