### ISSUE TITLE
Moon is fucked

### ISSUE THREAD

**Issue by romanwarlock** [MUME/MMapper#304]
Looks like 2 bloody morons Dain and Jahara marked as [A] made either MUME or Mmapper moon fucked.

**Comment by Kaspar-Metsa** [comment]
If anyone ever works on fixing the Moon after: https://mume.org/news/game/2704.php

Please also take a look at some ideas for MMapper2 related to moon in this issue: https://github.com/MUME/MMapper/issues/280

**Comment by Kaspar-Metsa** [comment]
The new moon cycle formula:
#define MOON_CYCLE_MINS = ((29 * MUD_HOURS_PER_DAY + 12) * MUD_MINS_PER_HOUR + 44)

It's the real world length of a synodic month rounded to minutes:
https://en.wikipedia.org/wiki/Lunar_month#Synodic_month

**Comment by nschimme** [comment]
Duplicate of https://github.com/MUME/MMapper/issues/312
