### ISSUE TITLE
Moon cycle change 2704 breaks MMapper2 moon counter

### ISSUE THREAD

**Issue by Kaspar-Metsa** [MUME/MMapper#312]
Dain changed the moon cycle: https://mume.org/news/game/2704.php

The new moon cycle formula:
#define MOON_CYCLE_MINS = ((29 * MUD_HOURS_PER_DAY + 12) * MUD_MINS_PER_HOUR + 44)

It's the real world length of a synodic month rounded to minutes:
https://en.wikipedia.org/wiki/Lunar_month#Synodic_month

This issue is to fix existing MMapper2 moon cycle functionality. When working on this please also consider some moon-related ideas mentioned here: https://github.com/MUME/MMapper/issues/280

**Comment by kasparAxual** [comment]
More information regarding new moon calculations that Dain (very) kindly provided:

*The moon's **position in the sky** (e.g., "moonrises in the east") and its **phase** (whether it's new/half/full) are completely different topics.*

**Dain**
> "First, the earth rotates one lap (taking... 24 hours). During that time, the moon has moved a bit. The earth needs to 
> catch up to that delta so it takes (MOON_CYCLE × 1d) ÷ (MOON_CYCLE - 1d) in total."

**Question**
I am sorry but can you bring an example how to use this formula please? What is "1d" and why are we multiplying MOON_CYCLE with "1d"?

**Dain**:
> 
> 1d is one (MUME) day.
> 
> Let's say you want the moon & earth to return to the same relative position (for example "moon rising in
> the east"). Assume they are in that position.
> 
> After additional time _t_, the earth has spun _t_ ÷ 1day revolutions. In the same time, the moon has spun
> _t_ ÷ 29d12h44min.
> 
> If you want their relative position to return to the same state, the earth needs to spin one revolution
> plus some fraction _f_, and that fraction has to equal how far the moon spun.
> 
>   f = t ÷ 1day - 1 = t ÷ 29d12h44min
> 
> Multiply both sides by (1day × 29d12h44min) and you get
> 
>   t × 29d12h44min - 1day × 29d12h44min = t × 1day
> 
> Move things around:
> 
>   t × 29d12h44min - t × 1day = 1day × 29d12h44min
> 
> Break out common factor:
> 
>   t × (29d12h44min - 1day) = 1day × 29d12h44min
> 
> and divide by (29d12h44min - 1day):
> 
>   t = (1day × 29d12h44min) ÷ (29d12h44min - 1day)

**Comment by kasparAxual** [comment]
**Question**
> If I understood correctly I remember you mentioned that it might not be possible to calculate next Full
> Moon rise in RL time?
>
> I think it is possible if I know:
>  1. MUME start epoch(2850 Jan 1 00:00 midnight)
>  2. Moon position at MUME start epoch(middle of full moon phase)
>  3. MUME time right now
>
> Am I missing something?

**Dain**
> It's not fully deterministic how fast MUME runs compared to real time. Due to game lag it might run
> slightly slower than it wants to. This effect should not be particularly big though.

**Comment by kasparAxual** [comment]
**Question**
> The time from the start of one phase to the next is: MOON_CYCLE/8 = 42524/8 = 5315.5 MUME minutes. I bet since it's in C it is rounded up.

No, there's no rounding. The moon only moves on integral game MUME minutes, but over time the correct
average will be maintained. It should be true on average (ignoring the computational error above).
