### ISSUE TITLE
Don't keep the MMapper connected to MUME if user closes the connection to MMapper

### ISSUE THREAD

**Issue by nschimme** [MUME/MMapper#4]
it would be nice if interruption of connection between client and mmapper was immediately propagated into interruption of connection between MMapper and MUME, so that user could go linkless from client without the need to shut down MMapper

**Comment by romanwarlock** [comment]
Trigger the client "Server closed the connection" to "disconnect()" / zap etc.

**Comment by nschimme** [comment]
This unfortunately is a limitation in MMapper until we allow offline emulation mode to not require a connection to MUME.

**Comment by nschimme** [comment]
Fixed! https://github.com/MUME/MMapper/commit/74cc0dd4e48d23627ad9e6b8a999e73589231f08
