### ISSUE TITLE
temporary exits

### ISSUE THREAD

**Issue by tomaswindsor** [MUME/MMapper#41]
We should be able to mark temporary exits in the map (they are common in new zones) and they should be rendered in a special way. Atm I am using "special" flag for them and also flag to tell mapper to ignore it for room matching (I think it's called "no match"), but a new flag would be nice, as "special" is too generic and I also use it for other features (like potentially webbed exits or exits blocked by mobiles or special features).

**Comment by nschimme** [comment]
I think temporary is the same as "no match". @teoli2003 can probably add more detail.

**Comment by tomaswindsor** [comment]
Truth is "no match" flag is of big help when mapping these, as it basically tells MMapper: "ignore this exit when syncing the map". 
Question is if the only use-case of this flag is a temporary exit. If so, then yes it can be used for this (and rendered somehow). If not, we need to add separate flag with similar behavior but with rendering.

To give few examples where this is useful:
- temporary exits in Old Forest Road area and Emyn-nu-Fuin
- Theddin's Mines in BM (where the labyrinth changes each pop, making most of the exits effectively temporary)
- places where \*trolls\* often dig with shovel (again, to prevent syncing issues)

**Comment by nschimme** [comment]
Please re-open if I didn't correctly implement what you wanted
