### ISSUE TITLE
We wish a death room highlight

### ISSUE THREAD

**Issue by romanwarlock** [MUME/MMapper#42]
Highlight the room where a character has died

**Comment by tomaswindsor** [comment]
Maybe generic temporary highlighting of current room via some _command would be enough. Then players could setup client actions to issue such _command on death messages.

**Comment by nschimme** [comment]
The cheapest way of doing this is to reuse the same selection criteria that was introduced in https://github.com/MUME/MMapper/pull/35

I can add a command like `_markcurrent` and also have `You are dead!` automatically run it.
