### ISSUE TITLE
Use gratuitous descs and get rid of _brief

### ISSUE THREAD

**Issue by waba4mume** [MUME/MMapper#47]
Mappers can now request to receive room descriptions from MUME, regardless of brief/spam character settings, see the `G` XML option at the bottom of `HELP MPI`.

This is meant as a user experience improvement: players won't have to fiddle with brief/spam to get a reliable room sync anymore, and you can get rid of that `_brief` client-side setting.

**Comment by nschimme** [comment]
Cool, I imagine this is a recent enhancement to the existing MPI protocol?

**Comment by waba4mume** [comment]
Yes :) I wanted something that Just Worked (tm) for the webclient.

I think that'll also solve 99% of the issues users may have getting MM2 to work, while simplifying the parsing code quite a bit. I'm not even sure why MM2 still has a text-mode parser and related input text color options...

NB: gratuitous descs are not sent when the character couldn't see them with "exa", for example a whitie in a moon-lit room.

**Comment by nschimme** [comment]
I took a stab at coding this. It wasn't too hard but I realized that we still need `m_brief` for the non-XML path. I'm considering deprecating that path to make the overall code base smaller.

**Comment by waba4mume** [comment]
I'm 100% for removing the non-XML parser, as I can't think of a valid usecase for it nowadays. That would make both the code and the config UI simpler.

I'll have a look at PR #50 soon, I hope.

**Comment by tomaswindsor** [comment]
Wouldn't it be sufficient to send a hash (e.g. md5) of the description for these purposes? It would reduce the net traffic at least...

**Comment by nschimme** [comment]
I imagine MUME doesn't have easily available md5 algorithm but that does make sense

**Comment by nschimme** [comment]
@waba4mume could add more details

**Comment by waba4mume** [comment]
The gratuitous desc completely replaces the normal desc when you play in brief mode.

So if I sent only a sum, mmapper couldn't perform loose matching (match rooms where the desc has been edited a bit). And then there is the mapping issue, as you mentioned.
