### ISSUE TITLE
Release 2.4.x

### ISSUE THREAD

**Issue by waba4mume** [MUME/MMapper#49]
Please make a compiled 2.4.x release that we can point new players to.

I just noticed that recent versions of my map with updated newbie areas are probably incompatible with the released 2.3.x versions as the file format changed.

Thanks!

**Comment by waba4mume** [comment]
That seems like a good idea, but I'd only include it in the releases' .zip/.msi/...

Large files maintained elsewhere have no business in a source repo, IMO.

**Comment by nschimme** [comment]
Noted, I'll probably need to strip out the old .zip and .mm2 binaries from the Git history as well at some point.

**Comment by nschimme** [comment]
I managed to unblock my Windows build with #30 and make some nice improvements with the Mac build as well. I'll try and get this out sometime over the holidays.

**Comment by nschimme** [comment]
Beta 1 has been released: https://github.com/MUME/MMapper/releases/tag/v2.4.0
