### ISSUE TITLE
Remove legacy OpenGL 1.x fixed function API usage

### ISSUE THREAD

**Issue by nschimme** [MUME/MMapper#63]
GL_POLYGON has also been deprecated and is in the current code

There are other examples that are mentioned in:
https://www.khronos.org/opengl/wiki/Legacy_OpenGL

**Comment by nschimme** [comment]
I've made some progress moving MMapper away from OpenGL 2.x and towards OpenGL 3.0. Moving to OpenGL 3.1 is going to be a much more difficult because of how MMapper is fond of use line primitives that are deprecated.

I am also unable to move entirely to modern OpenGL 3.2+ because OpenGL ES still doesn't support geometry shaders. I imagine we want to continue supporting older hardware so I might just have two versions of the MapCavas once I pull out as much of the fixed function code this is easily ripped out.

**Comment by nschimme** [comment]
I have some partial support in my shaders branch available here: https://github.com/nschimme/MMapper/tree/shaders

I am concerned about backwards compatibility so I haven't merged this into mainline yet. I'll have to do an extended beta test before I move forward.

**Comment by ulfhermann** [comment]
The whole point of modern OpenGL is to keep as much state as possible on the GPU and limit the draw calls. You can probably keep geometry for the whole room database [*] permanently on the GPU and just modify the projection and model/view matrices in each frame. Then you can draw the whole mess with exactly one draw call. This will also relieve you from the endless if/else stuff to select which room features to draw where. Those could just be encoded into the geometry. That is, MapCanvas::drawRoom() shouldn't be done on the CPU at all.

PS: Yes, I'm backseat driving ;) Ignore me.

[*] Was it 15k rooms? You can save 1000 bytes of extra stuff for each, and use about 15MB of GPU memory that way. Modern GPUs have Gigabytes of memory.

**Comment by nschimme** [comment]
@ulfhermann I'm completely new to 3D programming and I didn't consider that at all. I suppose this means we need to regenerate the world geometry on each room change during mapping mode?

**Comment by ulfhermann** [comment]
As a first iteration you can indeed just upload the whole room database for each change. That should still not be a problem for any GPU that isn't 20 years old. Later on you may want to partition the map and upload only the parts that actually changed. 

Maybe it's even feasible to use the geometry you upload as your primary data model. You'll certainly need to wrap that into some nicer API than the primitive datatypes OpenGL deals with, but if you do, you won't have to generate anything in order to upload it.

**Comment by fille** [comment]
looking att the code open gl code mmapper still using fixed pipeline?

**Comment by nschimme** [comment]
We're working on fixing this. No help needed for now...

**Comment by nschimme** [comment]
https://github.com/MUME/MMapper/commit/6154240e53e791da425f200ceb9aa9811f6660bd
