### ISSUE TITLE
First connection to group-manager server is unstable.

### ISSUE THREAD

**Issue by tomaswindsor** [MUME/MMapper#80]
Often when connecting to group manager, the connection will soon interrupt for some reason and you will be kicked out. Only then after you reconnect, it stays stable.

**Comment by nschimme** [comment]
I've noticed that the code also can crash if you switch between modes. I've refactored the code a bit to be cleaned and also moved it to a different thread. I'll see if I can release it as part of 2.4.3

**Comment by nschimme** [comment]
@tomaswindsor has this problem been fixed now in PR https://github.com/MUME/MMapper/pull/89 ?

**Comment by nschimme** [comment]
Please reopen if this is still an issue
