### ISSUE TITLE
Mapper stopped following in GH

### ISSUE THREAD

**Issue by henrikaavik** [MUME/MMapper#86]
For some reason mapper did not follow to Lhûn Street, normal named rooms were OK. Started working again when I changed encoding to ASCII. Maybe this û breaks it?

MacOS High Sierra 10.13.2 (17C88)

**Comment by nschimme** [comment]
What is your character encoding?

There is a new setting that @waba4mume added under 'Parser' called `"change charset" is:` that you'll need to modify.

@waba4mume I'm thinking about changing the default back to Latin-1 since that's the older setting.

**Comment by waba4mume** [comment]
@nschimme: Go ahead. I only made UTF-8 the default because that was matching the previous behavior of XML mode, so it seemed it would cause the least disruption. Most people seem to be playing in Latin-1 mode, though (from checking a few online players, I don't have real stats).

**Comment by nschimme** [comment]
@waba4mume  we could also introduce a new MPI command to select a particular character encoding:

The "C" Command
----

The C command requests a particular character encoding.

Modes:
 - A enables ASCII mode
 - U enables UTF-8 mode
 - L enables Latin-1 mode

Example 2:

```
~$#EC1
U
```

**Comment by waba4mume** [comment]
You would still need to manually synchronize the mmapper and client settings, though?

Or are you suggesting that the client sends that and mmapper snoops on it?


-------- Original Message --------

**Comment by nschimme** [comment]
Yeah, synchronization would still need to happen. Alternatively we could also create an MPI command where MUME tells MMapper that the character set changed. This is as opposed to MMapper requesting a certain character encoding which I proposed above.

**Comment by nschimme** [comment]
https://github.com/MUME/MMapper/commit/eff406966353911bd50ee1dbfbdc8101a7bda046 moves the MMapper default character set back to Latin-1

**Comment by nschimme** [comment]
I'll create a new issue to track character set autodetection

**Comment by nschimme** [comment]
@henrikaavik please change the setting back to Latin-1 and let us know if that fixed the issue
