### ISSUE TITLE
support for word of recall

### ISSUE THREAD

**Issue by tomaswindsor** [MUME/MMapper#92]
Rooms should have flags for word of recall spots (separate for whitie & darkie) and it would also be nice if word-spot-region boundaries were highlighted (edited either via exit flags manually or deduced from room->recall-room mappings).

**Comment by nschimme** [comment]
I noticed that in Faine's map he is currently doing this with notes. It makes sense to do in the mapper natively but I'm still trying to think of a way to overhaul the current room flag system as talked about in the issue #39.

**Comment by tomaswindsor** [comment]
The issue #39 is about implementation of random exits (room based vs exit based) and thus about possible overhaul of random exits in mmapper, not about overhaul of room flag system as a whole.

I am also mapping word spots via notes in my map currently (i am not mapping the boundaries). But both would be useful.

**Comment by nschimme** [comment]
https://github.com/MUME/MMapper/commit/879cc14be8a0c3e8d3c0026ac5c91e893ddeb35d
